default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 123456
  host: localhost

development:
  <<: *default
  database: my_database_development
  charset: utf8mb4
  collation: utf8mb4_general_ci
  encoding: utf8mb4

test:
  <<: *default
  database: my_database_test
